### ISSUE TITLE
Test suite doesn't compile with HTF 0.15

### ISSUE THREAD

**Issue by sternenseemann** [andrewufrank/uniform-error#1]
Fix and a constraint on uniform-error-0.1.3 would be helpful.

```
test/Uniform/Error_test.hs:34:7: error:
    Module ‘Test.Framework’ does not export ‘assertBool_’
   |
34 |     ( assertBool_,
   |       ^^^^^^^^^^^

test/Uniform/Error_test.hs:35:7: error:
    Module ‘Test.Framework’ does not export ‘assertEqual_’
   |
35 |       assertEqual_,
   |       ^^^^^^^^^^^^
```

**Comment by andrewufrank** [comment]
There were changes in HTF exports. I adaptet the code accordingly in a new version 0.1.3.1 which I just published. 
Thank you for spotting the problem!
